"resource/TFVRFirstTimeMovement.res"
{
	"MovementLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"MovementLabel"
		"xpos"				"22"
		"ypos"				"18"
		"wide"				"468"
		"tall"				"48"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Choose movement and comfort options. These are common first-time VR settings and can be adjusted later."
		"textAlignment"		"north-west"
		"wrap"				"1"
	}
	"LocomotionSourceLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"LocomotionSourceLabel"
		"xpos"				"22"
		"ypos"				"76"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Move direction"
		"textAlignment"		"west"
		"associate"			"LocomotionSource"
	}
	"LocomotionSource"
	{
		"ControlName"		"ComboBox"
		"fieldName"			"LocomotionSource"
		"xpos"				"22"
		"ypos"				"102"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"1"
		"editable"			"0"
	}
	"TurningModeLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"TurningModeLabel"
		"xpos"				"242"
		"ypos"				"76"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Turn mode"
		"textAlignment"		"west"
		"associate"			"TurningMode"
	}
	"TurningMode"
	{
		"ControlName"		"ComboBox"
		"fieldName"			"TurningMode"
		"xpos"				"242"
		"ypos"				"102"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"2"
		"editable"			"0"
	}
	"SnapTurnAngleLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"SnapTurnAngleLabel"
		"xpos"				"242"
		"ypos"				"140"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Snap turn angle"
		"textAlignment"		"west"
		"associate"			"SnapTurnAngle"
	}
	"SnapTurnAngle"
	{
		"ControlName"		"Slider"
		"fieldName"			"SnapTurnAngle"
		"xpos"				"242"
		"ypos"				"166"
		"wide"				"175"
		"tall"				"50"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"3"
		"leftText"			"15"
		"rightText"			"90"
	}
	"SmoothTurnRateLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"SmoothTurnRateLabel"
		"xpos"				"242"
		"ypos"				"140"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Smooth turn speed"
		"textAlignment"		"west"
		"associate"			"SmoothTurnRate"
	}
	"SmoothTurnRate"
	{
		"ControlName"		"Slider"
		"fieldName"			"SmoothTurnRate"
		"xpos"				"242"
		"ypos"				"166"
		"wide"				"175"
		"tall"				"50"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"4"
		"leftText"			"Slow"
		"rightText"			"Fast"
	}
	"ComfortVignette"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"ComfortVignette"
		"xpos"				"22"
		"ypos"				"220"
		"wide"				"220"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"5"
		"textAlignment"		"west"
	}
	"SeatedMode"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"SeatedMode"
		"xpos"				"22"
		"ypos"				"256"
		"wide"				"220"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"6"
		"textAlignment"		"west"
	}
}
