"resource/TFVROptionsSubControls.res"
{
	"PrimaryHandLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"PrimaryHandLabel"
		"xpos"				"22"
		"ypos"				"22"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Primary hand"
		"textAlignment"		"west"
		"associate"			"PrimaryHand"
	}
	"PrimaryHand"
	{
		"ControlName"		"ComboBox"
		"fieldName"			"PrimaryHand"
		"xpos"				"22"
		"ypos"				"46"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"1"
		"editable"			"0"
	}
	"LocomotionSourceLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"LocomotionSourceLabel"
		"xpos"				"22"
		"ypos"				"80"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Move direction"
		"textAlignment"		"west"
		"associate"			"LocomotionSource"
	}
	"LocomotionSource"
	{
		"ControlName"		"ComboBox"
		"fieldName"			"LocomotionSource"
		"xpos"				"22"
		"ypos"				"104"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"3"
		"editable"			"0"
	}
	"TurningModeLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"TurningModeLabel"
		"xpos"				"242"
		"ypos"				"22"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Turn mode"
		"textAlignment"		"west"
		"associate"			"TurningMode"
	}
	"TurningMode"
	{
		"ControlName"		"ComboBox"
		"fieldName"			"TurningMode"
		"xpos"				"242"
		"ypos"				"46"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"2"
		"editable"			"0"
	}
	"SmoothTurnRateLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"SmoothTurnRateLabel"
		"xpos"				"22"
		"ypos"				"162"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Smooth turn speed"
		"textAlignment"		"west"
		"associate"			"SmoothTurnRate"
	}
	"SmoothTurnRate"
	{
		"ControlName"		"Slider"
		"fieldName"			"SmoothTurnRate"
		"xpos"				"22"
		"ypos"				"186"
		"wide"				"175"
		"tall"				"50"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"5"
		"leftText"			"Slow"
		"rightText"			"Fast"
	}
	"SnapTurnAngleLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"SnapTurnAngleLabel"
		"xpos"				"242"
		"ypos"				"80"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Snap turn angle"
		"textAlignment"		"west"
		"associate"			"SnapTurnAngle"
	}
	"SnapTurnAngle"
	{
		"ControlName"		"ComboBox"
		"fieldName"			"SnapTurnAngle"
		"xpos"				"242"
		"ypos"				"104"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"4"
		"editable"			"0"
	}
	"MoveSensitivityLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"MoveSensitivityLabel"
		"xpos"				"22"
		"ypos"				"244"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Movement sensitivity"
		"textAlignment"		"west"
		"associate"			"MoveSensitivity"
	}
	"MoveSensitivity"
	{
		"ControlName"		"Slider"
		"fieldName"			"MoveSensitivity"
		"xpos"				"22"
		"ypos"				"268"
		"wide"				"175"
		"tall"				"50"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"7"
		"leftText"			"25"
		"rightText"			"200"
	}
	"ThumbstickDeadzoneLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"ThumbstickDeadzoneLabel"
		"xpos"				"242"
		"ypos"				"162"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Thumbstick deadzone"
		"textAlignment"		"west"
		"associate"			"ThumbstickDeadzone"
	}
	"ThumbstickDeadzone"
	{
		"ControlName"		"Slider"
		"fieldName"			"ThumbstickDeadzone"
		"xpos"				"242"
		"ypos"				"186"
		"wide"				"175"
		"tall"				"50"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"6"
		"leftText"			"0"
		"rightText"			"50"
	}
	"TurnDeadzoneLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"TurnDeadzoneLabel"
		"xpos"				"242"
		"ypos"				"244"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Turn deadzone"
		"textAlignment"		"west"
		"associate"			"TurnDeadzone"
	}
	"TurnDeadzone"
	{
		"ControlName"		"Slider"
		"fieldName"			"TurnDeadzone"
		"xpos"				"242"
		"ypos"				"268"
		"wide"				"175"
		"tall"				"50"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"8"
		"leftText"			"0"
		"rightText"			"80"
	}
	"WeaponSwitchStick"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"WeaponSwitchStick"
		"xpos"				"242"
		"ypos"				"322"
		"wide"				"220"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"9"
		"textAlignment"		"west"
	}
}
