"resource/TFVROptionsSubGameplay.res"
{
	"TwoHandGrip"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"TwoHandGrip"
		"xpos"				"22"
		"ypos"				"28"
		"wide"				"220"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"1"
		"textAlignment"		"west"
	}
	"OffhandGrip"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"OffhandGrip"
		"xpos"				"22"
		"ypos"				"64"
		"wide"				"220"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"2"
		"textAlignment"		"west"
	}
	"PhysicalThrow"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"PhysicalThrow"
		"xpos"				"22"
		"ypos"				"100"
		"wide"				"220"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"3"
		"textAlignment"		"west"
	}
	"PhysicalBall"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"PhysicalBall"
		"xpos"				"22"
		"ypos"				"136"
		"wide"				"220"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"4"
		"textAlignment"		"west"
	}
	"MouthActivate"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"MouthActivate"
		"xpos"				"242"
		"ypos"				"28"
		"wide"				"230"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"5"
		"textAlignment"		"west"
	}
	"VoiceGesture"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"VoiceGesture"
		"xpos"				"242"
		"ypos"				"64"
		"wide"				"230"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"6"
		"textAlignment"		"west"
	}
	"WeaponWallClip"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"WeaponWallClip"
		"xpos"				"242"
		"ypos"				"100"
		"wide"				"230"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"7"
		"textAlignment"		"west"
	}
}
