"resource/TFVROptionsSubComfort.res"
{
	"ComfortVignette"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"ComfortVignette"
		"xpos"				"22"
		"ypos"				"24"
		"wide"				"220"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"1"
		"textAlignment"		"west"
	}
	"VignetteStrengthLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"VignetteStrengthLabel"
		"xpos"				"22"
		"ypos"				"70"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Vignette strength"
		"textAlignment"		"west"
		"associate"			"VignetteStrength"
	}
	"VignetteStrength"
	{
		"ControlName"		"Slider"
		"fieldName"			"VignetteStrength"
		"xpos"				"22"
		"ypos"				"94"
		"wide"				"175"
		"tall"				"50"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"2"
		"leftText"			"Off"
		"rightText"			"Strong"
	}
	"PhysicalCrouch"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"PhysicalCrouch"
		"xpos"				"22"
		"ypos"				"154"
		"wide"				"220"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"3"
		"textAlignment"		"west"
	}
	"SeatedMode"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"SeatedMode"
		"xpos"				"22"
		"ypos"				"190"
		"wide"				"220"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"4"
		"textAlignment"		"west"
	}
	"PlayerHeightLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"PlayerHeightLabel"
		"xpos"				"242"
		"ypos"				"22"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Player height (inches)"
		"textAlignment"		"west"
		"associate"			"PlayerHeight"
	}
	"PlayerHeight"
	{
		"ControlName"		"Slider"
		"fieldName"			"PlayerHeight"
		"xpos"				"242"
		"ypos"				"46"
		"wide"				"175"
		"tall"				"50"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"5"
		"leftText"			"48"
		"rightText"			"84"
	}
	"WorldScaleLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"WorldScaleLabel"
		"xpos"				"242"
		"ypos"				"112"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"World scale"
		"textAlignment"		"west"
		"associate"			"WorldScale"
	}
	"WorldScale"
	{
		"ControlName"		"Slider"
		"fieldName"			"WorldScale"
		"xpos"				"242"
		"ypos"				"136"
		"wide"				"175"
		"tall"				"50"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"6"
		"leftText"			"Small"
		"rightText"			"Large"
	}
	"DynamicWorldScale"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"DynamicWorldScale"
		"xpos"				"242"
		"ypos"				"200"
		"wide"				"220"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"7"
		"textAlignment"		"west"
	}
}
