"resource/TFVROptionsSubVideo.res"
{
	"MirrorResolutionLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"MirrorResolutionLabel"
		"xpos"				"22"
		"ypos"				"22"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Mirror resolution"
		"textAlignment"		"west"
		"associate"			"MirrorResolution"
	}
	"MirrorResolution"
	{
		"ControlName"		"ComboBox"
		"fieldName"			"MirrorResolution"
		"xpos"				"22"
		"ypos"				"46"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"1"
		"editable"			"0"
	}
	"MSAALabel"
	{
		"ControlName"		"Label"
		"fieldName"			"MSAALabel"
		"xpos"				"242"
		"ypos"				"22"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"MSAA"
		"textAlignment"		"west"
		"associate"			"MSAA"
	}
	"MSAA"
	{
		"ControlName"		"ComboBox"
		"fieldName"			"MSAA"
		"xpos"				"242"
		"ypos"				"46"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"2"
		"editable"			"0"
	}
	"ForceMaxLOD"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"ForceMaxLOD"
		"xpos"				"242"
		"ypos"				"90"
		"wide"				"220"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"4"
		"textAlignment"		"west"
	}
	"HUDOnMirror"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"HUDOnMirror"
		"xpos"				"22"
		"ypos"				"126"
		"wide"				"220"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"5"
		"textAlignment"		"west"
	}
	"MenuOnMirror"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"MenuOnMirror"
		"xpos"				"22"
		"ypos"				"90"
		"wide"				"220"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"3"
		"textAlignment"		"west"
	}
}
