"resource/TFVROptionsSubSpectator.res"
{
	"SpectatorModeLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"SpectatorModeLabel"
		"xpos"				"22"
		"ypos"				"22"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Spectator camera"
		"textAlignment"		"west"
		"associate"			"SpectatorMode"
	}
	"SpectatorMode"
	{
		"ControlName"		"ComboBox"
		"fieldName"			"SpectatorMode"
		"xpos"				"22"
		"ypos"				"46"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"1"
		"editable"			"0"
	}
	"SpectatorZoomLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"SpectatorZoomLabel"
		"xpos"				"22"
		"ypos"				"104"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Mirror zoom"
		"textAlignment"		"west"
		"associate"			"SpectatorZoom"
	}
	"SpectatorZoom"
	{
		"ControlName"		"Slider"
		"fieldName"			"SpectatorZoom"
		"xpos"				"22"
		"ypos"				"128"
		"wide"				"175"
		"tall"				"50"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"3"
		"leftText"			"100%"
		"rightText"			"200%"
	}
	"SpectatorEyeLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"SpectatorEyeLabel"
		"xpos"				"242"
		"ypos"				"22"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Spectator view eye"
		"textAlignment"		"west"
		"associate"			"SpectatorEye"
	}
	"SpectatorEye"
	{
		"ControlName"		"ComboBox"
		"fieldName"			"SpectatorEye"
		"xpos"				"242"
		"ypos"				"46"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"2"
		"editable"			"0"
	}
	"RollSmoothingLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"RollSmoothingLabel"
		"xpos"				"242"
		"ypos"				"104"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Roll smoothing"
		"textAlignment"		"west"
		"associate"			"RollSmoothing"
	}
	"RollSmoothing"
	{
		"ControlName"		"Slider"
		"fieldName"			"RollSmoothing"
		"xpos"				"242"
		"ypos"				"128"
		"wide"				"175"
		"tall"				"50"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"4"
		"leftText"			"10 ms"
		"rightText"			"2 s"
	}
	"YawPitchSmoothingLabel"
	{
		"ControlName"		"Label"
		"fieldName"			"YawPitchSmoothingLabel"
		"xpos"				"22"
		"ypos"				"186"
		"wide"				"198"
		"tall"				"24"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Yaw/pitch smoothing"
		"textAlignment"		"west"
		"associate"			"YawPitchSmoothing"
	}
	"YawPitchSmoothing"
	{
		"ControlName"		"Slider"
		"fieldName"			"YawPitchSmoothing"
		"xpos"				"22"
		"ypos"				"210"
		"wide"				"175"
		"tall"				"50"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"5"
		"leftText"			"10 ms"
		"rightText"			"1 s"
	}
	"SpectatorExtras"
	{
		"ControlName"		"CheckButton"
		"fieldName"			"SpectatorExtras"
		"xpos"				"242"
		"ypos"				"190"
		"wide"				"220"
		"tall"				"36"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"6"
		"textAlignment"		"west"
	}
}
